#!/usr/bin/env python

TC_KEYS="/mnt/psk/keys"
TC_TEMPLATE="/mnt/psk/templates/Tamaki College Students"
DESTINATION="/etc/NetworkManager/system-connections/TC-Students"

import csv
import glob
import subprocess
import uuid

output = subprocess.Popen(['dmidecode','-s','system-serial-number'],stdout=subprocess.PIPE)
serial_number = output.stdout.read().strip()

for key_file in glob.glob(TC_KEYS + "/*"):
    with open( key_file, 'rb' ) as csvfile:
        csv_contents = csv.reader( csvfile, delimiter=',',quotechar='"' )
        for line in csv_contents:
            if line[0] == serial_number:
                print "Tamaki College Key Found"
                template = open(TC_TEMPLATE, 'r')
                output_list = []
                for line1 in template:
                    if line1.find( "__UUID__" ) != -1:
                        output_list.append( line1.replace( "__UUID__", str(uuid.uuid4()) ) )
                    elif line1.find( "__PSK__" ) != -1:
                        output_list.append( line1.replace( "__PSK__", line[2] ) )
                    else:
                        output_list.append( line1 )
                output_file = file( DESTINATION,'w')
                output_file.write( "".join(output_list) )
                output_file.close()
                subprocess.Popen(['chmod','600',DESTINATION])
