#!/bin/bash

RESPONSE="/tmp/response$$"
PKG_DIR="/mnt/live/pkg"
. "$PKG_DIR/variables"
PASSWORD='23TPVefOt0YPE'

$PKG_DIR/get_user 2>"$RESPONSE"
USER=$(<$RESPONSE)
[ ! -d $MOUNT_DIR ] && mkdir $MOUNT_DIR
[ -z "$( mount | grep "$MOUNT_DIR" | grep "$ROOT_PART" )" ] && \
    mount "$ROOT_PART" "$MOUNT_DIR"
chroot $MOUNT_DIR usermod -p "$PASSWORD" $USER
dialog --infobox "Password for $USER has been changed to password.\n\nPress any key to continue" 7 30
read -n1
[ -z "$( mount | grep "$MOUNT_DIR" | grep "$ROOT_PART" )" ] && \
    umount "$MOUNT_DIR"
